apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-web-deployment
  labels:
    app: personal-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personal-web
  template:
    metadata:
      labels:
        app: personal-web
    spec:
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
        - name: personal-web
          image: mdsahiloss/personal-web:latest
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: personal-web-svc
  labels:
    app: personal-web
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: personal-web

---
# ***************************To enable AutoScaling execute the below command****************************
# kubectl autoscale deployment personal-web-deployment --cpu-percent=80 --min=1 --max=10
