apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-web-deployment
  labels:
    app: personal-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personal-web
  template:
    metadata:
      labels:
        app: personal-web
    spec:
      containers:
        - name: personal-web
          image: 260009511791.dkr.ecr.us-east-1.amazonaws.com/personal-web:latest
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: personal-web-svc
  labels:
    app: personal-web
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
  selector:
    app: personal-web
