apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-web-deployment
  labels:
    app: personal-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personal-web
  template:
    metadata:
      labels:
        app: personal-web
    spec:
      containers:
        - name: personal-web
          image: 260009511791.dkr.ecr.us-east-1.amazonaws.com/personal-web:latest
          ports:
            - containerPort: 3000
