apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: personal-web-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: mdsahil-oss.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: personal-web-svc
                port:
                  number: 80
